before_script:
  - apt-get update && apt-get install -y nodejs

test_backend:
  image: python:3.7
  script:
    - pip install --upgrade pip
    - cd backend
    - pip install -r requirements.txt
    - python manage.py test
  services:
    - postgres:latest
  variables:
    SECRET_KEY: "notasecret"
    DB_NAME: "postgres"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    DB_HOST: "postgres"
    DB_PORT: "5432"

test_frontend:
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm run test:unit
    - npm run test:e2e
