version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    command: npm run build
    volumes:
      - ./frontend:/frontend
  backend:
    restart: always
    build: ./backend
    depends_on:
      - frontend
      - postgres
      - redis
    expose:
      - "8001"
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
      - static:/static
    env_file: backend/.env
    command: /backend/docker-entrypoint.sh

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/www/static

  postgres:
    restart: always
    image: postgres:11.5
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  static:
  pgdata:
  redisdata:
